### ISSUE TITLE
Horizontal Nav hover problem

### ISSUE THREAD

**Issue by HannahDelaney** [HannahDelaney/horizontal-nav#1]
Markbot is telling me that there is an issue with the nav hover in the index.html file, that it isn't functioning as expected. It says the background-color, color or border-color don't change when hovered, but as far as I can tell on the live site they do.

@thomasjbradley

**Comment by thomasjbradley** [comment]
The problem is that the `:hover` is attached to the `<li>` but it should be attached to the `<a>` tags. These lines here should target the `<a>` tags:
https://github.com/HannahDelaney/horizontal-nav/blob/gh-pages/css/main.css#L44-L46

**Comment by HannahDelaney** [comment]
Thank you, that fixed it!
